### ISSUE TITLE
Game crashes when recording video with bandicam

### ISSUE THREAD

**Issue by KhanhPhu572** [SkidderMC/FDPClient#1060]
**Describe the bug**
The game crashes when recording video with bandicam and the lag is not as smooth as before!

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Run FdpClient Latest Beta
2. Run Bandicam
3. Record and crash
4. BOOM blue screen error

**Expected behavior**
I want the staff to fix this error. From beta version bb7bbe3 #1825 onwards, all have the same error (I find that if recording video on Fdp client, currently beta bb7bbe3 is the best)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at net.ccbluex.liquidbounce.config.core.ConfigManager.load(ConfigManager.kt:55)
	at net.ccbluex.liquidbounce.config.core.ConfigManager.loadConfigSet(ConfigManager.kt:117)
	at net.ccbluex.liquidbounce.FDPClient.startClient(FDPClient.kt:211)
	at net.ccbluex.liquidbounce.ui.client.gui.GuiLaunchOptionSelectMenu.func_73866_w_(GuiLaunchOptionSelectMenu.kt:16)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.handler$displayGuiScreen$zzg000(Minecraft.java:3257)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:922)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 506716336 bytes (483 MB) / 1107296256 bytes (1056 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 7 total; -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_M5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	tlauncher_custom_cape_skin{1.4} [TLSkinCape] (tlskincape1.8.9-1.4.jar) 
	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape1.8.9-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
TransformerLoader (FDPClient-build.jar)
  net.ccbluex.liquidbounce.handler.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.100.9805' Renderer: 'Intel(R) UHD Graphics 630'
	Launched Version: fdp beta
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 30.0.100.9805, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §4 Dark Star 8x §4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9805
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 6
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [Latest beta]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- TLSkin

**Comment by Davidisnotavailable** [comment]
dont use bandicam

**Comment by KhanhPhu572** [comment]
I have used other video recording apps but the problem still persists

**Comment by opZywl** [comment]
Fixed in commit d0f4035e — configs are now written atomically (temp file + rename) and per-section saves are isolated, preventing corruption/crashes when saving is interrupted (e.g. during recording). Will be in the next build.
