### ISSUE TITLE
java.lang.NoSuchFieldError: JAVA_LETTER_OR_DIGIT

### ISSUE THREAD

**Issue by wxzex** [SkidderMC/FDPClient#1117]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Use Corretto JDK
2. Build FDP.
3. Run it.

**Expected behavior**
FDP client would launch.
**Screenshots/Video**
![image](https://github.com/SkidderMC/FDPClient/assets/130822426/910191ef-0e1f-4195-ac85-05faf2bc4fa1)

**Crash Report**
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.GL30.glGenFramebuffers(GL30.java:1157) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.renderer.OpenGlHelper.glGenFramebuffers(OpenGlHelper.java:707) ~[OpenGlHelper.class:?]
	at net.minecraft.client.shader.Framebuffer.createFramebuffer(Framebuffer.java:105) ~[Framebuffer.class:?]
	at net.minecraft.client.shader.Framebuffer.createBindFramebuffer(Framebuffer.java:58) ~[Framebuffer.class:?]
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:39) ~[Framebuffer.class:?]
	at net.ccbluex.liquidbounce.utils.SplashProgress.drawSplash(SplashProgress.kt:64) ~[SplashProgress.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.handler$run$zep000(SplashProgress.java:552) ~[SplashProgress$3.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java) ~[SplashProgress$3.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
[10:07:12] [Client thread/INFO]: Replaced 229 ore recipies
[10:07:12] [Client thread/INFO]: Reloading ResourceManager: Default
[10:07:12] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:529]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/18/24 10:07 AM
Description: Initializing game

java.lang.NoSuchFieldError: JAVA_LETTER_OR_DIGIT
	at net.minecraftforge.common.config.Configuration.<clinit>(Configuration.java:60)
	at net.minecraftforge.common.ForgeModContainer.<init>(ForgeModContainer.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:417)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95)
	at GradleStart.main(GradleStart.java:24)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.config.Configuration.<clinit>(Configuration.java:60)
	at net.minecraftforge.common.ForgeModContainer.<init>(ForgeModContainer.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95)
	at GradleStart.main(GradleStart.java:24)

**System Information**
        Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_402, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Amazon.com Inc.
	Memory: 1727238368 bytes (1647 MB) / 2042626048 bytes (1948 MB) up to 2042626048 bytes (1948 MB)
	JVM Flags: 2 total; -Xmx2048m -Xms2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 2 mods loaded, 0 mods active
**Other Installed Mods**
No mods installed

**Comment by PrahXZ** [comment]
Zywl FIX THIS!!! BROOOO

**Comment by vPrah** [comment]
Fixed, try it now
