### ISSUE TITLE
[Bug] SplashProgress has detected a error loading Minecraft.

### ISSUE THREAD

**Issue by DeezFurry** [SkidderMC/FDPClient#1121]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
The game crashed whilst initializing game
Error: SplashProgress has detected a error loading Minecraft.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Add the mod inside the mods folder
2. Launch the game with forge
3. Game loads modules
4. Game tries loading after but fails

**Expected behavior**
I expected FDP Client to bring me into the Main Menu.

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
![img](https://github.com/SkidderMC/FDPClient/assets/105929248/78babf74-ec4b-4eec-baa5-61b8d9607e5b)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-build.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 24/03/24 22.52
Description: Initializing game

SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabeled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
net.minecraftforge.fml.client.SplashProgress$5: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:516)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:571)
	... 10 more
Caused by: java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL30.glGenFramebuffers(GL30.java:1157)
	at net.minecraft.client.renderer.OpenGlHelper.func_153165_e(OpenGlHelper.java:707)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:105)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:58)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:39)
	at net.ccbluex.liquidbounce.utils.SplashProgress.drawSplash(SplashProgress.kt:64)
	at net.minecraftforge.fml.client.SplashProgress$3.handler$run$zeo000(SplashProgress.java:552)
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 6.5.0-26-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 315472872 bytes (300 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -Xverify:none -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	FDPClient{Release} [FDPClient] (FDPClient-build.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-build.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.handler.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1' Renderer: 'Mesa Intel(R) UHD Graphics 620 (WHL GT2)'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Mesa Intel(R) UHD Graphics 620 (WHL GT2) GL version 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, fabric, file/VanillaTweaks_r876796.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
```

**System Information**
 - OS: Ubuntu 23.10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: https://github.com/SkidderMC/FDPClient/actions/runs/8410972888

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
No, I don't have any other mods

**Additional info**
None.

**Comment by vPrah** [comment]
try it with the latest version, i think it has been fixed.
