### ISSUE TITLE
[Bug] <Freeze and crash , Signature "Bad video drivers" matches>

### ISSUE THREAD

**Issue by SmaamX** [SkidderMC/FDPClient#1170]
**Describe the bug**
Freeze and crash in loading (I try with and without Optifine then same result)

**To Reproduce**
1. Run minecraft launcher
2. Wait for loading
3. unknown render glitch in loading
4. freeze and hardcrash

**Expected behavior**
Empty

**Screenshots/Video**
Empty

**Crash Report**

```text
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 22.20.44.37.230215' Renderer: 'AMD Radeon(TM) Graphics'
[11:27:95] [Client thread/INFO]: MinecraftForge v11.15.1.1764 Initialized
[11:27:98] [Client thread/INFO]: Replaced 204 ore recipies
[11:27:23] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[11:27:23] [Client thread/INFO]: Searching C:\Users\SmaamX\AppData\Roaming\.minecraft\mods for mods
[11:27:89] [Client thread/INFO]: Mod FDPClient is missing the required element 'name'. Substituting FDPClient
[11:27:12] [VersionCheck/INFO]: [OptiFine] Version found: M5
[11:27:45] [Client thread/ERROR]: Unable to read a class file correctly
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:52)
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:69)
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:363)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[11:27:48] [Client thread/ERROR]: There was a problem reading the entry module-info.class in the jar C:\Users\SmaamX\AppData\Roaming\.minecraft\mods\FDPClient-build.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:58)
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:69)
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:363)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:52)
	... 16 more

[11:27:50] [Client thread/WARN]: Zip file FDPClient-build.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:58)
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:69)
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:363)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:52)
	... 16 more

[11:27:53] [Client thread/INFO]: Forge Mod Loader has identified 5 mods to load
[11:27:69] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, FDPClient, tlauncher_custom_cape_skin] at CLIENT
[11:27:69] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, FDPClient, tlauncher_custom_cape_skin] at SERVER
[11:27:93] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:FDPClient, FMLFileResourcePack:TLSkinCape
[11:27:96] [Client thread/INFO]: Processing ObjectHolder annotations
[11:27:97] [Client thread/INFO]: Found 384 ObjectHolder annotations
[11:27:97] [Client thread/INFO]: Identifying ItemStackHolder annotations
[11:27:97] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[11:27:02] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[11:27:03] [Client thread/INFO]: Applying holder lookups
[11:27:03] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[11:27:03] [Client thread/INFO]: Holder lookups applied
[11:27:03] [Client thread/INFO]: Injecting itemstacks
[11:27:03] [Client thread/INFO]: Itemstack injection complete
[11:27:04] [Client thread/INFO]: [OptiFine] *** Reloading textures ***
[11:27:11] [Client thread/INFO]: [OptiFine] Resource packs: Default
[11:27:23] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:27:45] [Thread-9/INFO]: Initializing LWJGL OpenAL
[11:27:45] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:27:93] [Thread-9/INFO]: OpenAL initialized.
[11:27:94] [Sound Library Loader/INFO]: Sound engine started
[11:27:23] [Client thread/INFO]: [OptiFine] Mipmap levels: 4
[11:27:25] [Client thread/INFO]: [OptiFine] Multitexture: false
[11:27:27] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_pane_white.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_white.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_pane_purple.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_purple.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_blue.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_pane_blue.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_brown.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_pane_brown.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_green.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_pane_green.properties
[11:27:29] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_pane_red.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_red.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_black.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_pane_black.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_orange.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_pane_orange.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_magenta.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_pane_magenta.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_light_blue.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_pane_light_blue.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_pane_yellow.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_yellow.properties
[11:27:30] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_lime.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_pane_lime.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pane_pink.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pink.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_gray.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_pane_gray.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_pane_silver.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_silver.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_cyan.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_pane_cyan.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/bookshelf.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glass.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glasspane.properties
[11:27:31] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/sandstone.properties
[11:27:32] [Client thread/INFO]: [OptiFine] Multipass connected textures: false
[11:27:32] [Client thread/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[11:27:33] [Client thread/INFO]: Created: 16x16 textures-atlas
[11:27:33] [Client thread/INFO]: [OptiFine] Animated sprites: 0
[11:28:61] [Client thread/INFO]: Injecting itemstacks
[11:28:61] [Client thread/INFO]: Itemstack injection complete
[11:28:85] [Client thread/INFO]: Forge Mod Loader has successfully loaded 5 mods
[11:28:85] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:FDPClient, FMLFileResourcePack:TLSkinCape
[11:28:88] [Client thread/INFO]: [OptiFine] *** Reloading textures ***
[11:28:89] [Client thread/INFO]: [OptiFine] Resource packs: Default
[11:28:02] [Client thread/INFO]: SoundSystem shutting down...
[11:28:25] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[11:28:26] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:28:46] [Thread-11/INFO]: Initializing LWJGL OpenAL
[11:28:46] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:28:73] [Thread-11/INFO]: OpenAL initialized.
[11:28:86] [Sound Library Loader/INFO]: Sound engine started
[11:28:51] [Client thread/INFO]: [OptiFine] Mipmap levels: 4
[11:28:51] [Client thread/INFO]: [OptiFine] Multitexture: false
[11:28:51] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_pane_white.properties
[11:28:51] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_white.properties
[11:28:51] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_pane_purple.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_purple.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_blue.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_pane_blue.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_brown.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_pane_brown.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_green.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_pane_green.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_pane_red.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_red.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_black.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_pane_black.properties
[11:28:52] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_orange.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_pane_orange.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_magenta.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_pane_magenta.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_light_blue.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_pane_light_blue.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_pane_yellow.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_yellow.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_lime.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_pane_lime.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pane_pink.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pink.properties
[11:28:53] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_gray.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_pane_gray.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_pane_silver.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_silver.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_cyan.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_pane_cyan.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/bookshelf.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glass.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glasspane.properties
[11:28:54] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/sandstone.properties
[11:28:54] [Client thread/INFO]: [OptiFine] Multipass connected textures: false
[11:28:54] [Client thread/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[11:28:85] [Client thread/INFO]: [OptiFine] Custom loader sprites: 1
[11:28:85] [Client thread/INFO]: [OptiFine] Custom loader sprites (skipped): 1
[11:28:89] [Client thread/INFO]: Created: 1024x512 textures-atlas
[11:28:92] [Client thread/INFO]: [OptiFine] Animated sprites: 11
[11:28:19] [Client thread/INFO]: Loading FDPClient v5.6.1
[11:28:19] [Client thread/INFO]: Initializing...
[11:28:13] [Client thread/INFO]: Loading language en_US
[11:28:25] [Client thread/INFO]: Loaded Fonts
[11:28:25] [Client thread/INFO]: Setting up default modules...
[11:28:34] [Client thread/INFO]: [ModuleManager] Loading modules...
[11:28:33] [Client thread/INFO]: [ModuleManager] Loaded 166 modules.
[11:28:53] [Client thread/INFO]: [FileManager] Loaded config: accounts.json.
[11:28:53] [Client thread/INFO]: [FileManager] Loaded config: friends.json.
[11:28:54] [Client thread/INFO]: [FileManager] Loaded config: special.json.
[11:28:55] [Client thread/INFO]: [FileManager] Loaded config: themeColor.json.
[11:28:56] [Client thread/INFO]: [FileManager] Loaded config: hud.json.
[11:28:56] [Client thread/INFO]: [FileManager] Loaded config: xray-blocks.json.
[11:28:57] [Client thread/INFO]: FDPClient v5.6.1 loaded in 46384ms!
[11:28:54] [Client thread/INFO]: [FileManager] Loaded config: clickgui.json.
[11:28:56] [Client thread/ERROR]: DiscordRPC failed to start
[11:28:78] [Client thread/INFO]: Config default.json loaded.
[11:28:78] [Client thread/INFO]: FDPClient v5.6.1 started!
[11:28:84] [Thread-16/INFO]: New version available: b31989d
[11:28:02] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[11:28:26] [Client thread/INFO]: [OptiFine] *** Reloading custom textures ***
[11:28:36] [Client thread/INFO]: [OptiFine] Enable face culling: acacia_leaves, birch_leaves, dark_oak_leaves, jungle_leaves, oak_leaves, spruce_leaves
[11:29:02] [Timer-0/INFO]: Config default.json saved.
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (118 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1073741819
flush now
[Launcher] [Crash] Signature "Bad video drivers" matches!
[Crash] Signature "Bad video drivers" matches!
[Launcher] [Crash] Signature "Bad video drivers" matches!
[Crash] Signature "Bad video drivers" matches!
[Launcher] [Crash] Found crash report file: C:\Users\SmaamX\AppData\Roaming\.minecraft\crash-reports\crash-2024-04-30_11.16.21-client.txt
[Crash] Found crash report file: C:\Users\SmaamX\AppData\Roaming\.minecraft\crash-reports\crash-2024-04-30_11.16.21-client.txt
[Launcher] [Crash] Crash has been recognized!
[Crash] Crash has been recognized!
```

**System Information**
 - OS: [Windows 10(11) amd64 version 10.0]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.1764]
 - FDPClient Version: [5.6.1]
 - JVM Flags: [7 total; -Xmx7582M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0]
- Memory: [323893888 bytes (308 MB) / 671088640 bytes (640 MB) up to 7952400384 bytes (7584 MB)]
- Java Version: [1.8.0_51, Oracle Corporation]
- Java VM Version: [Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation]

**Other Installed Mods**
- <OptiFine-OptiFine-1.8.9_HD_U_M5>

**Additional info**
Empty

**Comment by SmaamX** [comment]
> Update your graphics drivers

I will try

**Comment by vPrah** [comment]
Download DDU utility and uninstall your drivers, reboot and install your drivers

**Comment by SmaamX** [comment]
> Download DDU utility and uninstall your drivers, reboot and install your drivers

Problem fixed, thanks
