### ISSUE TITLE
[Bug] 我用的1.8.9的版本，加了forge就是进不去

### ISSUE THREAD

**Issue by lcxws** [SkidderMC/FDPClient#1217]
进不去，这是日志，进度调满了就崩了
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (9654d301-772a-44e8-b633-104c3ef12399.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 24-8-29 下午9:26
Description: Initializing game

java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-8,5,main] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_421, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 958738944 bytes (914 MB) / 1282408448 bytes (1223 MB) up to 6549405696 bytes (6246 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn936m -Xmx6246m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (9654d301-772a-44e8-b633-104c3ef12399.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 532.10' Renderer: 'NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2'
	Launched Version: 1.8.9-Forge_11.15.1.2318
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 532.10, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900HX

**Comment by boysir** [comment]
人才

**Comment by opZywl** [comment]
From the crash report a coremod (TransformerLoader) is present — another mod/coremod is conflicting during Forge startup. Launch with only FDPClient (+ViaForge if needed). Closing as a mod conflict.

— FDPClient maintainers
