### ISSUE TITLE
Network Crash

### ISSUE THREAD

**Issue by idTxjWBaVu** [SkidderMC/FDPClient#1256]
FDPCLIENT crash info
Client version: b10 git-4969e7a
Time: 2024-12-22T12:31:16.375
Operating System: Windows 10 (Version: 10.0, Arch: amd64)
Java Version: 1.8.0_422 (Vendor: Azul Systems, Inc.)
Available Processors: 8
Max Memory: 4096 MB
Free Memory: 391 MB
Total Memory: 979 MB

--- Stacktrace ---
kotlin.UninitializedPropertyAccessException: lateinit property fontSmall has not been initialized
	at net.ccbluex.liquidbounce.ui.font.Fonts.getFontSmall(Fonts.kt:34)
	at net.ccbluex.liquidbounce.ui.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.kt:246)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1437)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:112)
	at oolloo.jlw.Wrapper.main(Wrapper.java:105)

**Comment by RaditPro24** [comment]
Please help me when I open the client, it force closes
