### ISSUE TITLE
[BUG] Game crashed ExceptionInInitializerError

### ISSUE THREAD

**Issue by Noonenowhoiam** [SkidderMC/FDPClient#1258]
my game was crashing when joining any server crash report

--- Game crash info ---
  Client: FDPCLIENT b11 (git-7657156)
Time: 2024-12-31T14:20:42.877
OS: Windows 10 (Version: 10.0, Arch: amd64)
Java: 1.8.0_51 (Vendor: Oracle Corporation)
Available Processors: 4
Max Memory: 3008 MB
Free Memory: 675 MB
Total Memory: 1120 MB
--- Stacktrace ---
java.lang.ExceptionInInitializerError
	at net.ccbluex.liquidbounce.features.module.modules.client.HUDModule.onRender2D$lambda$22(HUDModule.kt:122)
	at net.ccbluex.liquidbounce.features.module.modules.client.HUDModule$$Lambda$1153/1743322261.invoke(Unknown Source)
	at net.ccbluex.liquidbounce.event.EventManager.processEvent(EventManager.kt:127)
	at net.ccbluex.liquidbounce.event.EventManager.call(EventManager.kt:149)
	at net.minecraft.client.gui.GuiIngame.liquidBounce$injectRender2DEvent(GuiIngame.java:1498)
	at net.minecraft.client.gui.GuiIngame.handler$injectCustomHotbar$zbg000(GuiIngame.java:1471)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:297)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:120)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1396)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.IOException: Couldn't find local font file: C:\Users\Nirob Noben\AppData\Roaming\.minecraft2\FDPCLIENT\fonts\Inter_Medium.ttf
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager$FontRegistry.readFontFromLocal(SimpleFontManager.kt:69)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager$FontRegistry.fontFamily$lambda$0(SimpleFontManager.kt:55)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager$FontRegistry$$Lambda$4878/1944055376.invoke(Unknown Source)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager$FontRegistry.fontFamily$lambda$1(SimpleFontManager.kt:53)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager$FontRegistry$$Lambda$4879/1852440863.apply(Unknown Source)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager$FontRegistry.fontFamily(SimpleFontManager.kt:53)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.SimpleFontManager.fontFamily(SimpleFontManager.kt:30)
	at net.ccbluex.liquidbounce.ui.font.fontmanager.impl.Fonts$InterMedium.<clinit>(Fonts.kt:52)
	... 19 more

**Comment by opZywl** [comment]
Fixed in commit 38b1b116 — a missing local font file now falls back to a default font instead of crashing. Will be in the next build.
