### ISSUE TITLE
FDP Client Crashing

### ISSUE THREAD

**Issue by SourCream95** [SkidderMC/FDPClient#22]
######################### FDP CRASH REPORT #########################

If this problem persists, please send this file to the FDPClient developers! Website (where you can join the discord server): http://FDPClient.Club/
This file will be saved in ".minecraft/FDPCrashLogs.txt"

 | ????????????????????????!  --Apache????
 | Troubleshooting any problem without the error log is like driving with your eyes closed.
 | From Apache official documentation Getting Started chapter
   - INFO:
   |   Version: git-8574f26
   |   Time: 1657278550223
   |   OS: WINDOWS

######################### FDP CRASH REPORT #########################
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-8574f26.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/8/22 6:09 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:375)
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:370)
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376)
	at java.util.TreeMap.getEntry(TreeMap.java:345)
	at java.util.TreeMap.get(TreeMap.java:278)
	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:192)
	at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:121)
	at com.google.common.collect.TreeMultimap.put(TreeMultimap.java:78)
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:386)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:364)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:375)
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:370)
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376)
	at java.util.TreeMap.getEntry(TreeMap.java:345)
	at java.util.TreeMap.get(TreeMap.java:278)
	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:192)
	at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:121)
	at com.google.common.collect.TreeMultimap.put(TreeMultimap.java:78)
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:386)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:364)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 147307440 bytes (140 MB) / 402653184 bytes (384 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 4 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
		Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
		null{1.0} [null] (Inertia Client 3.1.3 - 1.16.5.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-8574f26.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	Launched Version: Forge 1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ThirtyVirus Pack V4.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 512.15
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	
	help

**Comment by DinoFengz** [comment]
render bug i think

**Comment by FDPUser443** [comment]
remove (Inertia Client 3.1.3 - 1.16.5.jar) from mods folder;
