### ISSUE TITLE
[Bug] <FDP 4.5.5 didn't want to load by Forge(Means not Loaded).>

### ISSUE THREAD

**Issue by ProSteve12301** [SkidderMC/FDPClient#331]
Fix it Please ;-)

**Comment by nuym** [comment]
[17:13:43] [main/ERROR]: Unable to read the jar file FDPClient-v4.5.5.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_341]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_341]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_341]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_341]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_341]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:334) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
