### ISSUE TITLE
[Bug] Unable to load scripts

### ISSUE THREAD

**Issue by CMCat-Xicheng** [SkidderMC/FDPClient#337]
like what i said in title

[10:08:48] [Client thread/ERROR]: [ScriptAPI] Failed to load script 'AntiLagBackFixed.js'.
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.ccbluex.liquidbounce.FDPClient
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397) ~[ScriptRuntime.class:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449) ~[NashornScriptEngine.class:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406) ~[NashornScriptEngine.class:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402) ~[NashornScriptEngine.class:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155) ~[NashornScriptEngine.class:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[?:1.8.0_261]
	at net.ccbluex.liquidbounce.script.Script.supportLegacyScripts(Script.kt:132) ~[Script.class:?]
	at net.ccbluex.liquidbounce.script.Script.<init>(Script.kt:71) ~[Script.class:?]
	at net.ccbluex.liquidbounce.script.ScriptManager.loadJsScript(ScriptManager.kt:54) [ScriptManager.class:?]
	at net.ccbluex.liquidbounce.script.ScriptManager.loadScripts(ScriptManager.kt:29) [ScriptManager.class:?]
	at net.ccbluex.liquidbounce.launch.data.modernui.GuiScriptLoadMenu.func_73864_a(GuiScriptLoadMenu.java:91) [GuiScriptLoadMenu.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555) [axu.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524) [axu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) [ave.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.ccbluex.liquidbounce.FDPClient
	at jdk.nashorn.internal.runtime.Context.findClass(Context.java:1040) ~[Context.class:?]
	at jdk.nashorn.internal.objects.NativeJava.simpleType(NativeJava.java:498) ~[NativeJava.class:?]
	at jdk.nashorn.internal.objects.NativeJava.type(NativeJava.java:322) ~[NativeJava.class:?]
	at jdk.nashorn.internal.objects.NativeJava.type(NativeJava.java:314) ~[NativeJava.class:?]
	at jdk.nashorn.internal.objects.NativeJava.type(NativeJava.java:310) ~[NativeJava.class:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$11$3180$\^eval\_._ModuleManager(<eval>:157) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$10$\^eval\_.:program(<eval>:341) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) ~[ScriptFunctionData.class:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[ScriptFunction.class:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[ScriptRuntime.class:?]
	... 22 more

**System Information**
 - OS:  Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: FDPClient-463cb7e

**Comment by CMCat-Xicheng** [comment]
very serious problem

**Comment by CMCat-Xicheng** [comment]
Script have no problem working on LB and old FDP
