### ISSUE TITLE
Fix HUD + Huddesigner

### ISSUE THREAD

**Issue by DinoFengz** [SkidderMC/FDPClient#43]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 
2. 
3. 
4. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
######################### FDP CRASH REPORT #########################

If this problem persists, please send this file to the FDPClient developers! Website (where you can join the discord server): http://fdpinfo.github.io/
This file will be saved in ".minecraft/FDPCrashLogs.txt"

 | 在没有错误日志的情况下诊断任何问题无异于闭眼开车!  --Apache官方文档
 | Troubleshooting any problem without the error log is like driving with your eyes closed.
 | From Apache official documentation Getting Started chapter
   - INFO:
   |   Version: git-2ef2cc1
   |   Time: 1657783373438
   |   OS: WINDOWS

######################### FDP CRASH REPORT #########################
---- Minecraft Crash Report ----
// Don't do that.

Time: 7/14/22 3:22 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: Could not initialize class net.ccbluex.liquidbounce.utils.render.BlurUtils
	at net.ccbluex.liquidbounce.ui.client.hud.element.elements.Notification.drawNotification(Notifications.kt:156)
	at net.ccbluex.liquidbounce.ui.client.hud.element.elements.Notifications.drawElement(Notifications.kt:56)
	at net.ccbluex.liquidbounce.ui.client.hud.HUD.render(HUD.kt:66)
	at net.ccbluex.liquidbounce.ui.client.hud.designer.GuiHudDesigner.drawScreen(GuiHudDesigner.kt:29)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1104)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.run(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95)
	at GradleStart.main(GradleStart.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ccbluex.liquidbounce.ui.client.hud.element.elements.Notification.drawNotification(Notifications.kt:156)
	at net.ccbluex.liquidbounce.ui.client.hud.element.elements.Notifications.drawElement(Notifications.kt:56)
	at net.ccbluex.liquidbounce.ui.client.hud.HUD.render(HUD.kt:66)
	at net.ccbluex.liquidbounce.ui.client.hud.designer.GuiHudDesigner.drawScreen(GuiHudDesigner.kt:29)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)

-- Screen render details --
Details:
	Screen name: net.ccbluex.liquidbounce.ui.client.hud.designer.GuiHudDesigner
	Mouse location: Scaled: (480, 254). Absolute: (960, 508)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 6 total; [EntityPlayerSP['DinoFengZ81'/445020, l='MpServer', x=-6.23, y=200.00, z=-4.70], EntityOtherPlayerMP['3MMid'/445028, l='MpServer', x=0.78, y=200.00, z=-6.31], EntityOtherPlayerMP['lukamikava12'/445033, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['Adelgamer657'/445049, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['3rb2'/445048, l='MpServer', x=4.13, y=200.00, z=-0.97], EntityOtherPlayerMP['enterrzao'/445062, l='MpServer', x=0.50, y=200.00, z=-8.50]]
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,89.00,0.00 - World: (0,89,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 26418463 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntityOtherPlayerMP['enterrzao'/445062, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['3MMid'/445028, l='MpServer', x=0.78, y=200.00, z=-6.31], EntityOtherPlayerMP['3rb2'/445048, l='MpServer', x=4.13, y=200.00, z=-0.97], EntityPlayerSP['DinoFengZ81'/445020, l='MpServer', x=-6.23, y=200.00, z=-4.70], EntityOtherPlayerMP['lukamikava12'/445033, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['Adelgamer657'/445049, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['3rb2'/445048, l='MpServer', x=4.13, y=200.00, z=-0.97], EntityOtherPlayerMP['enterrzao'/445062, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['3MMid'/445028, l='MpServer', x=0.78, y=200.00, z=-6.31], EntityOtherPlayerMP['lukamikava12'/445033, l='MpServer', x=0.50, y=200.00, z=-8.50], EntityOtherPlayerMP['Adelgamer657'/445049, l='MpServer', x=0.50, y=200.00, z=-8.50]]
	Retry entities: 0 total; []
	Server brand: FlameCord <- BlocksMC
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:347)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.run(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95)
	at GradleStart.main(GradleStart.java:24)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_331, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 245870616 bytes (234 MB) / 1007157248 bytes (960 MB) up to 1007157248 bytes (960 MB)
	JVM Flags: 2 total; -Xmx1024m -Xms1024m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar) 
	Loaded coremods (and transformers): 
TransformerLoader (unknown)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !         §3§lR§b§lB§3§lW §8[§f16x§8].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [latest gith]

**Comment by DinoFengz** [comment]
@opZywl
