### ISSUE TITLE
[Bug] Crash Report

### ISSUE THREAD

**Issue by ItzOverS** [SkidderMC/FDPClient#564]
**Description**
FDP Client get crashed when a click on "Client" section to open it, my client crashed...

**What did I do?**
1.  I created a new config using command : ".config create Vulcan2"
2.  Then I press right shift & right click on "Client" section to change it ui
3.  It get hang for a while & then crashed

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-5.0.0b.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/16/22 1:31 PM
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Module.drawScreen(Module.java:50)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Tab.lambda$drawScreen$0(Tab.java:61)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Tab$$Lambda$40/1169369933.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Tab.drawScreen(Tab.java:61)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.DropdownGUI.func_73863_a(DropdownGUI.java:92)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1437)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Module.drawScreen(Module.java:50)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Tab.lambda$drawScreen$0(Tab.java:61)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Tab$$Lambda$40/1169369933.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.Tab.drawScreen(Tab.java:61)
	at net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.DropdownGUI.func_73863_a(DropdownGUI.java:92)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)

-- Screen render details --
Details:
	Screen name: net.ccbluex.liquidbounce.launch.data.modernui.clickgui.style.styles.dropdown.DropdownGUI
	Mouse location: Scaled: (516, 116). Absolute: (1032, 769)
	Screen size: Scaled: (960, 501). Absolute: (1920, 1001). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_OverLight_'/41, l='MpServer', x=-800.87, y=70.17, z=862.28]]
	Chunk stats: MultiplayerChunkCache: 30, 30
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 20.00,64.00,120.00 - World: (20,64,120), Chunk: (at 4,4,8 in 1,7; contains blocks 16,0,112 to 31,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 102787 game time, 102787 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntitySkeleton['Skeleton'/64, l='MpServer', x=-800.28, y=57.00, z=831.97], EntitySkeleton['Skeleton'/65, l='MpServer', x=-797.44, y=53.00, z=875.06], EntitySkeleton['Skeleton'/66, l='MpServer', x=-788.50, y=53.00, z=870.50], EntityZombie['Zombie'/68, l='MpServer', x=-772.72, y=24.00, z=825.44], EntitySpider['Spider'/69, l='MpServer', x=-769.72, y=27.09, z=831.66], EntitySkeleton['Skeleton'/70, l='MpServer', x=-770.50, y=23.00, z=833.50], EntitySkeleton['Skeleton'/71, l='MpServer', x=-770.50, y=23.00, z=834.50], EntitySkeleton['Skeleton'/72, l='MpServer', x=-771.50, y=23.00, z=833.50], EntityCreeper['Creeper'/73, l='MpServer', x=-765.97, y=28.16, z=842.44], EntityZombie['Zombie'/74, l='MpServer', x=-767.88, y=31.00, z=849.19], EntityBat['Bat'/75, l='MpServer', x=-764.25, y=22.94, z=842.88], EntityItem['item.tile.torch'/76, l='MpServer', x=-765.84, y=22.00, z=819.56], EntityMinecartChest['container.minecart'/77, l='MpServer', x=-766.50, y=22.06, z=819.50], EntityZombie['Zombie'/78, l='MpServer', x=-766.50, y=22.00, z=831.50], EntitySkeleton['Skeleton'/79, l='MpServer', x=-761.50, y=22.00, z=829.50], EntityCreeper['Creeper'/80, l='MpServer', x=-764.50, y=23.00, z=845.50], EntitySkeleton['Skeleton'/81, l='MpServer', x=-765.50, y=23.00, z=849.50], EntitySkeleton['Skeleton'/82, l='MpServer', x=-763.50, y=23.00, z=852.50], EntityZombie['Zombie'/83, l='MpServer', x=-766.28, y=31.00, z=848.56], EntitySkeleton['Skeleton'/230, l='MpServer', x=-778.50, y=25.00, z=836.50], EntityPlayerSP['_OverLight_'/41, l='MpServer', x=-800.87, y=70.17, z=862.28], EntityZombie['Zombie'/43, l='MpServer', x=-836.34, y=11.00, z=864.88], EntityEnderman['Enderman'/44, l='MpServer', x=-827.94, y=11.00, z=875.44], EntityBat['Bat'/47, l='MpServer', x=-823.66, y=15.06, z=813.81], EntityCreeper['Creeper'/53, l='MpServer', x=-808.50, y=35.00, z=837.50], EntityCreeper['Creeper'/54, l='MpServer', x=-810.50, y=35.00, z=837.50], EntitySkeleton['Skeleton'/249, l='MpServer', x=-777.50, y=25.00, z=838.50], EntitySkeleton['Skeleton'/250, l='MpServer', x=-775.72, y=25.00, z=844.47], EntitySkeleton['Skeleton'/251, l='MpServer', x=-765.53, y=23.00, z=844.84], EntityCreeper['Creeper'/61, l='MpServer', x=-795.50, y=48.00, z=829.50], EntityCreeper['Creeper'/62, l='MpServer', x=-792.53, y=60.00, z=842.69], EntitySkeleton['Skeleton'/63, l='MpServer', x=-791.50, y=60.00, z=839.28]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 210331952 bytes (200 MB) / 805306368 bytes (768 MB) up to 939524096 bytes (896 MB)
	JVM Flags: 7 total; -Xmx887M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 17, tallocated: 89
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_M5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	fpsspoofmod{1.01} [FPS Spoofer Mod] (FPS-Spoofer-Mod-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-5.0.0b.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	Launched Version: FDP Client
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce MX130/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ! §cRose Revamp §7[32x].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce MX130/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: latest ( I THINK )
 - FDPClient Version: 5.0.0b

**Other Installed Mods**
- FPS-Spoofer-Mod-1.8.9
- OptiFine-1.8.9_HD_U_M5

**Comment by gatooooooo** [comment]
## suspected issue
bug relating to dropdown clickgui "classic"
## for [ItzOverS](https://github.com/ItzOverS) as a temporary fix
try .clickgui style LiquidBounce
this will switch you to a basic clickgui

**Comment by C00LC0D35** [comment]
yez
