### ISSUE TITLE
[Bug]FDP v5.1.0 crash

### ISSUE THREAD

**Issue by Ds1nk** [SkidderMC/FDPClient#640]
When you open Animation Setting in LB+ ClickGUI.

How to crash game:
1. Use LB+ ClickGUI
2. Open Animation Setting
3. BOOM.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-build8acb695.jar)
Contact their authors BEFORE contacting forge

// Surprise motherfu**er.

Time: 22-11-26 上午11:49
Description: Rendering screen

java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -2.0 is less than minimum 0.0.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1131)
	at net.ccbluex.liquidbounce.ui.client.gui.newVer.element.module.value.impl.FloatElement.drawElement(FloatElement.kt:35)
	at net.ccbluex.liquidbounce.ui.client.gui.newVer.element.module.ModuleElement.drawElement(ModuleElement.kt:112)
	at net.ccbluex.liquidbounce.ui.client.gui.newVer.element.CategoryElement.drawPanel(CategoryElement.kt:60)
	at net.ccbluex.liquidbounce.ui.client.gui.clickgui.style.styles.newVer.NewUi.drawFullSized(NewUi.java:133)
	at net.ccbluex.liquidbounce.ui.client.gui.clickgui.style.styles.newVer.NewUi.func_73863_a(NewUi.java:78)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1437)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1131)
	at net.ccbluex.liquidbounce.ui.client.gui.newVer.element.module.value.impl.FloatElement.drawElement(FloatElement.kt:35)
	at net.ccbluex.liquidbounce.ui.client.gui.newVer.element.module.ModuleElement.drawElement(ModuleElement.kt:112)
	at net.ccbluex.liquidbounce.ui.client.gui.newVer.element.CategoryElement.drawPanel(CategoryElement.kt:60)
	at net.ccbluex.liquidbounce.ui.client.gui.clickgui.style.styles.newVer.NewUi.drawFullSized(NewUi.java:133)
	at net.ccbluex.liquidbounce.ui.client.gui.clickgui.style.styles.newVer.NewUi.func_73863_a(NewUi.java:78)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)

-- Screen render details --
Details:
	Screen name: net.ccbluex.liquidbounce.ui.client.gui.clickgui.style.styles.newVer.NewUi
	Mouse location: Scaled: (902, 125). Absolute: (1804, 807)
	Screen size: Scaled: (960, 529). Absolute: (1920, 1057). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['Ky19ry_g65o85u'/30551, l='MpServer', x=4.34, y=200.00, z=-12.27], EntityOtherPlayerMP['gfwertgvse6539'/30415, l='MpServer', x=9.22, y=200.00, z=-1.56], EntityOtherPlayerMP['fucking19'/30495, l='MpServer', x=6.69, y=200.65, z=2.53], EntityOtherPlayerMP['Dabman0797'/30647, l='MpServer', x=-1.91, y=200.12, z=-4.45], EntityOtherPlayerMP['ULTIMATE_KILLA'/30766, l='MpServer', x=10.16, y=199.91, z=-13.09], EntityOtherPlayerMP['jinyu_QWO'/30809, l='MpServer', x=11.12, y=200.22, z=-10.83], EntityOtherPlayerMP['hasdbhj14214'/30823, l='MpServer', x=12.41, y=200.00, z=-1.41], EntityOtherPlayerMP['Aegro_D867'/30908, l='MpServer', x=4.59, y=200.00, z=-0.47], EntityOtherPlayerMP['IanTzy13'/31080, l='MpServer', x=6.50, y=200.00, z=-15.50]]
	Chunk stats: MultiplayerChunkCache: 439, 439
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 6.00,104.00,-7.00 - World: (6,104,-7), Chunk: (at 6,6,9 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 846 game time, 14005 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 17 total; [EntityPlayerSP['Ky19ry_g65o85u'/30551, l='MpServer', x=4.34, y=200.00, z=-12.27], EntityOtherPlayerMP['hasdbhj14214'/30823, l='MpServer', x=12.41, y=200.00, z=-1.41], EntityOtherPlayerMP['Aegro_D867'/30908, l='MpServer', x=4.59, y=200.00, z=-0.47], EntityOtherPlayerMP['IanTzy13'/31080, l='MpServer', x=6.50, y=200.00, z=-15.50], EntityOtherPlayerMP['jinyu_QWO'/30809, l='MpServer', x=11.12, y=200.22, z=-10.83], EntityOtherPlayerMP['ULTIMATE_KILLA'/30766, l='MpServer', x=10.16, y=199.91, z=-13.09], EntityOtherPlayerMP['gfwertgvse6539'/30415, l='MpServer', x=9.22, y=200.00, z=-1.56], EntityOtherPlayerMP['Dabman0797'/30647, l='MpServer', x=-1.91, y=200.12, z=-4.45], EntityOtherPlayerMP['Dabman0797'/30647, l='MpServer', x=-1.91, y=200.12, z=-4.45], EntityOtherPlayerMP['ULTIMATE_KILLA'/30766, l='MpServer', x=10.16, y=199.91, z=-13.09], EntityOtherPlayerMP['gfwertgvse6539'/30415, l='MpServer', x=9.22, y=200.00, z=-1.56], EntityOtherPlayerMP['fucking19'/30495, l='MpServer', x=6.69, y=200.65, z=2.53], EntityOtherPlayerMP['jinyu_QWO'/30809, l='MpServer', x=11.12, y=200.22, z=-10.83], EntityOtherPlayerMP['Aegro_D867'/30908, l='MpServer', x=4.59, y=200.00, z=-0.47], EntityOtherPlayerMP['hasdbhj14214'/30823, l='MpServer', x=12.41, y=200.00, z=-1.41], EntityOtherPlayerMP['IanTzy13'/31080, l='MpServer', x=6.50, y=200.00, z=-15.50], EntityOtherPlayerMP['fucking19'/30495, l='MpServer', x=6.69, y=200.65, z=2.53]]
	Retry entities: 0 total; []
	Server brand: FlameCord <- BlocksMC
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 280039952 bytes (267 MB) / 1073741824 bytes (1024 MB) up to 7147094016 bytes (6816 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx6816m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-build8acb695.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	Launched Version: FDPClient
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Blockhit_Overlay(1).zip, §dFadeless §c[§f64x§c].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by MatrixAura** [comment]
It's fixed in latest

**Comment by MatrixAura** [comment]
It's been fixed in latest

**Comment by MatrixAura** [comment]
@opZywl close it

**Comment by MatrixAura** [comment]
@opZywl close it plz
