### ISSUE TITLE
[Fdp Crash] Crash

### ISSUE THREAD

**Issue by downloadyetter** [SkidderMC/FDPClient#821]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (CrossSine-B31.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/4/23 3:29 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at net.ccbluex.liquidbounce.utils.ClassUtils.getObjectInstance(ClassUtils.kt:32)
	at net.ccbluex.liquidbounce.features.module.ModuleManager.registerModule(ModuleManager.kt:71)
	at net.ccbluex.liquidbounce.features.module.ModuleManager.registerModules(ModuleManager.kt:39)
	at net.ccbluex.liquidbounce.LiquidBounce.initClient(LiquidBounce.kt:168)
	at net.minecraft.client.Minecraft.handler$startGame$zzl000(Minecraft.java:3189)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.EnumConstantNotPresentException: net.ccbluex.liquidbounce.features.module.ModuleCategory.MISC
	at sun.reflect.annotation.EnumConstantNotPresentExceptionProxy.generateException(EnumConstantNotPresentExceptionProxy.java:46)
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:83)
	at com.sun.proxy.$Proxy21.category(Unknown Source)
	at net.ccbluex.liquidbounce.features.module.Module.<init>(Module.kt:85)
	at net.ccbluex.liquidbounce.features.module.modules.misc.Insult.<init>(Insult.kt:26)
	at net.ccbluex.liquidbounce.features.module.modules.misc.Insult.<clinit>(Insult.kt)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at net.ccbluex.liquidbounce.utils.ClassUtils.getObjectInstance(ClassUtils.kt:32)
	at net.ccbluex.liquidbounce.features.module.ModuleManager.registerModule(ModuleManager.kt:71)
	at net.ccbluex.liquidbounce.features.module.ModuleManager.registerModules(ModuleManager.kt:39)
	at net.ccbluex.liquidbounce.LiquidBounce.initClient(LiquidBounce.kt:168)
	at net.minecraft.client.Minecraft.handler$startGame$zzl000(Minecraft.java:3189)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 793935832 bytes (757 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	CrossSine{1.0} [CrossSine] (CrossSine-B31.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (CrossSine-B31.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 531.79' Renderer: 'NVIDIA GeForce GT 1030/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 531.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 531.79
	OpenGlRenderer: NVIDIA GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Davidisnotavailable** [comment]
(CrossSine-B31.jar) issue

**Comment by downloadyetter** [comment]
> 

should i reinstall forge

**Comment by ineedcheatsrn** [comment]
> > 
> 
> should i reinstall forge

this is a CrossSine issue, not an fdp issue
