### ISSUE TITLE
error when building fdp client

### ISSUE THREAD

**Issue by wxzex** [SkidderMC/FDPClient#907]
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_372]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]

**Comment by RtxOP** [comment]
Send the entire stacktrace this doesn't help
